ALTER SESSION SET NLS_LANGUAGE = 'BRAZILIAN PORTUGUESE';

CREATE TABLE "RODRIGO_RODRIGUES"."HSTIPONOTIFICACAO" (
   "ID" NUMBER(3) GENERATED ALWAYS AS IDENTITY
        CONSTRAINT "HSTIPONOTIFICACAO_NN" NOT NULL
        CONSTRAINT "HSTIPONOTIFICACAO_PK" PRIMARY KEY,
    "DESCRICAO" VARCHAR2(100),
    "NOME_INTERNO" VARCHAR2(200),
    "ASSUNTO" VARCHAR2(200),
    "CORPO" VARCHAR2(4000),
    "ATIVA" CHAR(1)
);

CREATE TABLE "RODRIGO_RODRIGUES"."HSTIPONOTIFICACAORESPOSTA" (
    "ID" NUMBER(4) GENERATED ALWAYS AS IDENTITY 
        CONSTRAINT "HSTIPONOTIFICACAORESPOSTA_NN" NOT NULL
        CONSTRAINT "HSTIPONOTIFICACAORESPOSTA_PK" PRIMARY KEY,
    "ID_TIPO_NRESPOSTA" NUMBER(3)
        CONSTRAINT "HSTIPONOTIFICACAORESPOSTAO_TIPONOTIFICACAO_FK" REFERENCES RODRIGO_RODRIGUES.HSTIPONOTIFICACAO ("ID"), -- chave estrang ID_TIPO que referencia ID em HSTIPONOTIFICACAO
    "DESCRICAO" VARCHAR2(100),
    "COMANDO" VARCHAR2(4000),
    "ATIVA" CHAR(1)
);

CREATE TABLE "RODRIGO_RODRIGUES"."HSNOTIFICACAO" (
    "ID" NUMBER(7) GENERATED ALWAYS AS IDENTITY
        CONSTRAINT "HSNOTIFICACAO_NN" NOT NULL
        CONSTRAINT "HSNOTIFICACAO_PK" PRIMARY KEY,
    "ID_TIPO_NOTIFICACAO" NUMBER(3)
        CONSTRAINT "HSNOTIFICACAO_TIPONOTIFICACAO_FK" REFERENCES RODRIGO_RODRIGUES.HSTIPONOTIFICACAO ("ID"), 
    "ID_RESPOSTA" NUMBER(4)
        CONSTRAINT "HSNOTIFICACAO_NOTIFICACAORESPOSTA_FK" REFERENCES RODRIGO_RODRIGUES.HSTIPONOTIFICACAORESPOSTA ("ID"), 
    "DATA_CRIACAO" DATE,
    "ORIGEM" VARCHAR2(100),
    "DATA_LIMITE" DATE,
    "ASSUNTO" VARCHAR2(200),
    "CORPO" VARCHAR2(4000),
    "COMANDO" VARCHAR2(4000)
);